version: '3'

services:

  python:
    build: ./python3
    volumes:
      - ./python3:/work
    expose:
      - "3031"
    depends_on:
      - db
  
  db:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo
      MYSQL_USER: worker
      MYSQL_PASSWORD: worker
      TZ: 'Asia/Tokyo'
  
  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    links:
      - python
    depends_on:
      - python

  # front:
  #   build:
  #     context: ./front
  #   command: 'sh /app/start.sh'
  #   volumes:
  #     - ./front:/app/:cached
  #     - ./front/node_modules:/app/node_modules
  #   ports:
  #     - "8080:8080"